"""Remove empresa_id para mono-empresa

Revision ID: 0e2642936df0
Revises: bead4e7a5869
Create Date: 2026-01-15 13:07:26.901652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2642936df0'
down_revision: Union[str, Sequence[str], None] = 'bead4e7a5869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departamentos_empresa_id_fkey'), 'departamentos', type_='foreignkey')
    op.drop_column('departamentos', 'empresa_id')
    op.drop_constraint(op.f('jobs_empresa_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'empresa_id')
    op.drop_constraint(op.f('users_empresa_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'empresa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_empresa_id_fkey'), 'users', 'empresas', ['empresa_id'], ['id'])
    op.add_column('jobs', sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('jobs_empresa_id_fkey'), 'jobs', 'empresas', ['empresa_id'], ['id'])
    op.add_column('departamentos', sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('departamentos_empresa_id_fkey'), 'departamentos', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###
