"""add profile entities: candidaturas jobs activities contracts documents histories

Revision ID: 2bd562f303d7
Revises: 51f3d59c98ba
Create Date: 2026-01-12 11:22:32.557024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd562f303d7'
down_revision: Union[str, Sequence[str], None] = '51f3d59c98ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('etapa_atual', sa.String(length=100), nullable=True),
    sa.Column('nota_media', sa.String(length=10), nullable=True),
    sa.Column('feedback_resumo', sa.Text(), nullable=True),
    sa.Column('data_candidatura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidaturas_id'), 'candidaturas', ['id'], unique=False)
    op.create_table('contract_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('salario', sa.String(length=50), nullable=True),
    sa.Column('novo_dept', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_histories_data'), 'contract_histories', ['data'], unique=False)
    op.create_index(op.f('ix_contract_histories_id'), 'contract_histories', ['id'], unique=False)
    op.create_table('daily_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('evento', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_histories_data'), 'daily_histories', ['data'], unique=False)
    op.create_index(op.f('ix_daily_histories_id'), 'daily_histories', ['id'], unique=False)
    op.create_table('employee_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=255), nullable=True),
    sa.Column('salario_atual', sa.String(length=50), nullable=True),
    sa.Column('data_admissao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employee_contracts_id'), 'employee_contracts', ['id'], unique=False)
    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_data'), 'user_activities', ['data'], unique=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_data'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_table('employee_documents')
    op.drop_index(op.f('ix_employee_contracts_id'), table_name='employee_contracts')
    op.drop_table('employee_contracts')
    op.drop_index(op.f('ix_daily_histories_id'), table_name='daily_histories')
    op.drop_index(op.f('ix_daily_histories_data'), table_name='daily_histories')
    op.drop_table('daily_histories')
    op.drop_index(op.f('ix_contract_histories_id'), table_name='contract_histories')
    op.drop_index(op.f('ix_contract_histories_data'), table_name='contract_histories')
    op.drop_table('contract_histories')
    op.drop_index(op.f('ix_candidaturas_id'), table_name='candidaturas')
    op.drop_table('candidaturas')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
