"""final models for PersonProfile tabs

Revision ID: 51bc0dc1c584
Revises: 2bd562f303d7
Create Date: 2026-01-12 15:50:01.425772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51bc0dc1c584'
down_revision: Union[str, Sequence[str], None] = '2bd562f303d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_pdi_id'), 'pdi', ['id'], unique=False)
    op.add_column('candidaturas', sa.Column('data', sa.String(length=10), nullable=True))
    op.add_column('candidaturas', sa.Column('empresa', sa.String(length=255), nullable=True))
    op.add_column('candidaturas', sa.Column('vaga', sa.String(length=255), nullable=True))
    op.drop_column('candidaturas', 'data_candidatura')
    op.alter_column('contract_histories', 'data',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_contract_histories_data'), table_name='contract_histories')
    op.alter_column('daily_histories', 'data',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_index(op.f('ix_daily_histories_data'), table_name='daily_histories')
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.create_index(op.f('ix_daily_histories_data'), 'daily_histories', ['data'], unique=False)
    op.alter_column('daily_histories', 'data',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index(op.f('ix_contract_histories_data'), 'contract_histories', ['data'], unique=False)
    op.alter_column('contract_histories', 'data',
               existing_type=sa.String(length=10),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('candidaturas', sa.Column('data_candidatura', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('candidaturas', 'vaga')
    op.drop_column('candidaturas', 'empresa')
    op.drop_column('candidaturas', 'data')
    op.drop_index(op.f('ix_pdi_id'), table_name='pdi')
    op.drop_table('pdi')
    # ### end Alembic commands ###
