"""add pretensao_salarial to users

Revision ID: 51f3d59c98ba
Revises: 5fc6b3dec6d7
Create Date: 2026-01-12 10:30:29.761721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f3d59c98ba'
down_revision: Union[str, Sequence[str], None] = '5fc6b3dec6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pretensao_salarial', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pretensao_salarial')
    # ### end Alembic commands ###
