"""Add details to Job

Revision ID: ce89b3155a20
Revises: 51bc0dc1c584
Create Date: 2026-01-13 13:45:52.936151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce89b3155a20'
down_revision: Union[str, Sequence[str], None] = '51bc0dc1c584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'evento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('candidaturas', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('candidaturas', 'etapa_atual',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('candidaturas', 'nota_media',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('candidaturas', 'data',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_candidaturas_id'), table_name='candidaturas')
    op.alter_column('contract_histories', 'data',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('contract_histories', 'evento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('contract_histories', 'salario',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_contract_histories_id'), table_name='contract_histories')
    op.alter_column('daily_histories', 'data',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('daily_histories', 'evento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('daily_histories', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_daily_histories_id'), table_name='daily_histories')
    op.alter_column('employee_contracts', 'salario_atual',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_employee_contracts_id'), table_name='employee_contracts')
    op.alter_column('employee_documents', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('employee_documents', 'arquivo_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_employee_documents_id'), table_name='employee_documents')
    op.alter_column('empresas', 'cnpj',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint(op.f('empresas_cnpj_key'), 'empresas', type_='unique')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.add_column('jobs', sa.Column('prazo', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('resumo', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('descricao', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('requisitos', sa.Text(), nullable=True))
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_pdi_id'), table_name='pdi')
    op.alter_column('user_activities', 'acao',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_activities_data'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_id'), table_name='user_activities')
    op.alter_column('users', 'cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=255),
               comment=None,
               existing_comment='Somente números, sem pontos ou traços',
               existing_nullable=False)
    op.alter_column('users', 'telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'consentimento_lgpd',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'pretensao_salarial',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'pretensao_salarial',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'consentimento_lgpd',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'telefone',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'cpf',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=11),
               comment='Somente números, sem pontos ou traços',
               existing_nullable=False)
    op.create_index(op.f('ix_user_activities_id'), 'user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_user_activities_data'), 'user_activities', ['data'], unique=False)
    op.alter_column('user_activities', 'acao',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_pdi_id'), 'pdi', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('jobs', 'requisitos')
    op.drop_column('jobs', 'descricao')
    op.drop_column('jobs', 'resumo')
    op.drop_column('jobs', 'prazo')
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_unique_constraint(op.f('empresas_cnpj_key'), 'empresas', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.alter_column('empresas', 'cnpj',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.create_index(op.f('ix_employee_documents_id'), 'employee_documents', ['id'], unique=False)
    op.alter_column('employee_documents', 'arquivo_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('employee_documents', 'status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_employee_contracts_id'), 'employee_contracts', ['id'], unique=False)
    op.alter_column('employee_contracts', 'salario_atual',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_daily_histories_id'), 'daily_histories', ['id'], unique=False)
    op.alter_column('daily_histories', 'status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('daily_histories', 'evento',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('daily_histories', 'data',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_contract_histories_id'), 'contract_histories', ['id'], unique=False)
    op.alter_column('contract_histories', 'salario',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contract_histories', 'evento',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('contract_histories', 'data',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_candidaturas_id'), 'candidaturas', ['id'], unique=False)
    op.alter_column('candidaturas', 'data',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('candidaturas', 'nota_media',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('candidaturas', 'etapa_atual',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('candidaturas', 'status',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('audit_logs', 'evento',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
